import {
  TOKENS_COLORS,
  TOKENS_COLOR_PALETTE,
  TOKENS_COLOR_SLIDERS
} from './colors';
import { TOKENS_ICONS } from './icons';
import { TOKENS_SPACERS } from './spacers';

export const ThymeTokens = {
  COLORS: TOKENS_COLORS,
  COLOR_PALETTE: TOKENS_COLOR_PALETTE,
  COLOR_SLIDERS: TOKENS_COLOR_SLIDERS,
  ICONS: TOKENS_ICONS,
  SPACERS: TOKENS_SPACERS,
};
